
package xhx.demo.webservice.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AreaServiceImplService", targetNamespace = "http://impl.service.webservice.demo.xhx/", wsdlLocation = "http://127.0.0.1:12345/area?wsdl")
public class AreaServiceImplService
    extends Service
{

    private final static URL AREASERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException AREASERVICEIMPLSERVICE_EXCEPTION;
    private final static QName AREASERVICEIMPLSERVICE_QNAME = new QName("http://impl.service.webservice.demo.xhx/", "AreaServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:12345/area?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AREASERVICEIMPLSERVICE_WSDL_LOCATION = url;
        AREASERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public AreaServiceImplService() {
        super(__getWsdlLocation(), AREASERVICEIMPLSERVICE_QNAME);
    }

    public AreaServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AREASERVICEIMPLSERVICE_QNAME, features);
    }

    public AreaServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, AREASERVICEIMPLSERVICE_QNAME);
    }

    public AreaServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AREASERVICEIMPLSERVICE_QNAME, features);
    }

    public AreaServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AreaServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AreaServiceImpl
     */
    @WebEndpoint(name = "AreaServiceImplPort")
    public AreaServiceImpl getAreaServiceImplPort() {
        return super.getPort(new QName("http://impl.service.webservice.demo.xhx/", "AreaServiceImplPort"), AreaServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AreaServiceImpl
     */
    @WebEndpoint(name = "AreaServiceImplPort")
    public AreaServiceImpl getAreaServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.webservice.demo.xhx/", "AreaServiceImplPort"), AreaServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AREASERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw AREASERVICEIMPLSERVICE_EXCEPTION;
        }
        return AREASERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
